# Generated by Django 4.0.3 on 2022-05-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_rename_user_profile_alter_chat_creator_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='users_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
