# Generated by Django 4.0.3 on 2022-05-10 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('startpage', '0006_alter_chat_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users_id',
        ),
        migrations.CreateModel(
            name='UserChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='startpage.chat')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
