# Generated by Django 4.0.3 on 2022-05-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0007_remove_chat_users_id_userchats'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
