# Generated by Django 4.0.3 on 2022-05-16 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0008_profile_last_seen_alter_profile_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='online',
        ),
    ]
