# Generated by Django 4.0.3 on 2022-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0011_delete_test_remove_chat_creator_id_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.CharField(default='1.jpeg', max_length=200),
        ),
    ]
