# Generated by Django 4.0.3 on 2022-05-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0012_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
